### ISSUE TITLE
To-do List just for the Panda

### ISSUE THREAD

**Issue by cherry2003** [MrBilly/Tr1pw1re-Bots#1]
- [x] Update announcement
- [ ] Do more work on Tr1pw1re-RoleManager in C# (rewrite from Java)
- [x] Add helpop command (C#)
- [x] Add promote command (C#) 
- [x] **Suggestion: Command to opt-out of NSFW** #6
😃

**Comment by MrBilly** [comment]
- [ ] Possibly do something with

```
.Parameter("msg", ParameterType.Unparsed)
.Do(async e =>
{
    var msg = e.GetArg("msg")?.Trim();
    MemoryStream ms = new MemoryStream();
    var sw = new StreamWriter(ms);
    sw.WriteLine(msg);
    sw.Flush();
    sw.BaseStream.Position = 0;
    await e.Channel.SendFile(DateTime.Now.ToString("hh-mm_dd-MM-yyyy") + ".txt", sw.BaseStream);
});
```

**Comment by MrBilly** [comment]
**Announcement has been updated** @cherry2003 
**With the help of** 42e5103

**Comment by 820bry** [comment]
**Role Manager partially added with Evolva**

**Comment by MrBilly** [comment]
- [ ] **Suggestion: Command to opt-out of NSFW** #6
- [ ] **!yellow, !green, !blue, !indigo, !turquoise, !purple, !pink, !black** #7
